name: Build IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app
        sudo xcodebuild -license accept

    - name: Build IPA
      run: |
        xcodebuild -workspace MangaReader.xcworkspace -scheme MangaReader -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/MangaReader.xcarchive
        xcodebuild -exportArchive -archivePath $PWD/build/MangaReader.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: MangaReader.ipa
        path: build/MangaReader.ipa
