name: Build IOS
on:
  workflow_dispatch: {}

jobs:
  build_ios:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app

    - name: Install dependencies
      run: |
        gem install cocoapods

    - name: Build .xcarchive
      run: |
        xcodebuild clean archive \
          -workspace MangaReader.xcworkspace \
          -scheme MangaReader \
          -configuration Release \
          -archivePath ./build/MangaReader.xcarchive \

    - name: Upload .ipa
      uses: actions/upload-artifact@v4
      with:
        name: app-ios.ipa
        path: ./build/YourApp.ipa
